# Generated by Django 4.2 on 2023-06-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0003_alter_student_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='User',
        ),
    ]
